version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurant
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      INGREDIENT_SERVICE_URL: http//localhost:5000
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  menu_db:
    extends:
      file: menu-service/docker-compose.yml
      service: menu_db
  menu_service:
    extends:
      file: menu-service/docker-compose.yml
      service: service





#  menu_db:
#    container_name: menu_db
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    healthcheck:
#      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
#      timeout: 4s
#      retries: 60
#    volumes:
#      - ./menu_service_db:/var/lib/mysql
#
#  menu_service:
#      container_name: menu_service
#      links:
#        - menu_db
#      depends_on:
#        - menu_db
#      build: .
#      ports:
#        - "5000:5000"
#






#  menu_db:
#    container_name: menu_db
#    image: mysql:5.7
#    # ports:
#    #     - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    healthcheck:
#      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
#      timeout: 4s
#      retries: 60
#    volumes:
#      - ./menu_service_db:/var/lib/mysql
#  service:
#    container_name: menu_service
#    links:
#      - menu_db
#    depends_on:
#      menu_db:
#        condition: service_healthy
#    build: .
#    ports:
#      - "5000:5000"
#volumes:
#  menu_service_db: